### ISSUE TITLE
Stuck on - Connected to server

### ISSUE THREAD

**Issue by raffysommy** [ArthurFDLR/BR-M5#1]
Hey Arthur,
Thanks a lot for this project.
I managed to pair the ESP32 with my Canon M50.
Unfortunately everything works only on the first pairing.
When I turn off the camera and the esp32 on reboot I get:
```
BLE device found: 
c4:ac:59:2f:ff:38
 - Found Canon M50
 - Scan completed
Forming a connection to c4:ac:59:2f:ff:38
 - Connected to server
```
And the software stucks there.
Did you find the same behavior?
Thanks

**Comment by ArthurFDLR** [comment]
Hey Raffaele, sorry for getting back to you after so long. I just updated the source code with some major fixes. It might also solve your issue.
